In [1]:
from __future__ import print_function
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, precision_score, recall_score
import numpy as np
import pandas as pd

In [14]:
def read_data(path):
    with open(path, "r") as f:
        lines = f.readlines()
        lines = [x.strip() for x in lines if not x.startswith("I")]
        data = [x.split(" ") for x in lines]
        data = np.array(data).astype(float)
        data = pd.DataFrame(data)
    return data

In [15]:
data = read_data("D:/Code/python/mat3533/practice02/data/vidu3_lin_reg.txt")
print(data)

        0     1     2      3     4     5     6
0     1.0  56.0  21.0  160.0  14.0  6.00  1.95
1     2.0  76.0  18.0  150.0  12.0  4.97  1.33
2     3.0  63.0  16.0  160.0   4.4  6.39  0.83
3     4.0  78.0  20.0  100.0   4.0  7.00  2.00
4     5.0  87.0  20.0  110.0   4.6  4.10  1.30
..    ...   ...   ...    ...   ...   ...   ...
95   96.0  55.0  24.0  160.0   5.0  7.20  0.90
96   97.0  76.0  15.0  140.0   3.1  5.24  1.16
97   98.0  70.0  25.0  180.0   4.0  4.40  1.00
98   99.0  85.0  21.0  160.0   5.2  5.20  0.97
99  100.0  87.0  22.0  130.0   9.0  5.20  2.30

[100 rows x 7 columns]


In [27]:
x = data.iloc[:, 1:6]
y = data[6]
x = np.array(x)
y = np.array([y]).T

In [28]:
print(x)

[[ 56.    21.   160.    14.     6.  ]
 [ 76.    18.   150.    12.     4.97]
 [ 63.    16.   160.     4.4    6.39]
 [ 78.    20.   100.     4.     7.  ]
 [ 87.    20.   110.     4.6    4.1 ]
 [ 76.    19.   150.     4.6    2.74]
 [ 55.    31.   160.     5.5    4.6 ]
 [ 74.    22.   100.     6.8    5.04]
 [ 81.    21.   120.     5.8    4.75]
 [ 77.    24.   160.     5.4    6.94]
 [ 29.    20.   120.     3.8    4.84]
 [ 71.    22.   160.     3.3    6.63]
 [ 77.    21.   160.     5.1    4.93]
 [ 59.    18.   150.     6.     4.55]
 [ 58.    27.   130.     6.9    6.7 ]
 [ 34.    19.   130.     4.5    3.2 ]
 [ 74.    22.   100.    10.6    4.3 ]
 [ 61.    19.   170.    18.     6.8 ]
 [ 53.    20.   130.    25.     5.5 ]
 [ 65.    28.   140.     6.5    6.8 ]
 [ 80.    19.   160.     4.8    5.74]
 [ 71.    25.   160.     6.2    6.9 ]
 [ 90.    24.   160.     4.7    7.  ]
 [ 44.    24.   120.     6.     3.4 ]
 [ 91.    27.   150.     6.1    4.92]
 [ 75.    22.   160.     6.2    6.08]
 [ 60.    24

In [29]:
print(y)

[[1.95]
 [1.33]
 [0.83]
 [2.  ]
 [1.3 ]
 [1.16]
 [1.  ]
 [1.  ]
 [0.8 ]
 [1.6 ]
 [0.65]
 [1.  ]
 [0.97]
 [0.73]
 [1.1 ]
 [1.1 ]
 [1.1 ]
 [0.8 ]
 [0.99]
 [1.  ]
 [1.13]
 [1.  ]
 [1.7 ]
 [0.9 ]
 [0.89]
 [0.8 ]
 [0.81]
 [1.2 ]
 [0.82]
 [0.89]
 [1.19]
 [0.97]
 [0.97]
 [0.97]
 [0.88]
 [0.97]
 [0.9 ]
 [0.89]
 [0.8 ]
 [1.13]
 [1.2 ]
 [0.9 ]
 [0.81]
 [0.8 ]
 [0.74]
 [2.66]
 [0.89]
 [0.79]
 [0.8 ]
 [0.56]
 [0.8 ]
 [1.2 ]
 [0.82]
 [0.9 ]
 [1.  ]
 [1.15]
 [1.16]
 [0.97]
 [0.8 ]
 [1.67]
 [1.06]
 [1.1 ]
 [0.8 ]
 [1.7 ]
 [0.99]
 [1.16]
 [0.62]
 [1.  ]
 [0.82]
 [1.  ]
 [1.7 ]
 [2.3 ]
 [0.89]
 [0.97]
 [0.7 ]
 [1.1 ]
 [1.01]
 [1.15]
 [0.92]
 [1.1 ]
 [0.8 ]
 [0.7 ]
 [1.  ]
 [0.8 ]
 [0.89]
 [0.6 ]
 [1.5 ]
 [0.7 ]
 [1.1 ]
 [0.81]
 [0.7 ]
 [0.71]
 [2.7 ]
 [1.13]
 [1.7 ]
 [0.9 ]
 [1.16]
 [1.  ]
 [0.97]
 [2.3 ]]


In [34]:
x_train = x[:80]
y_train = y[:80]
x_test = x[80:]
y_test = y[80:]

In [35]:
one = np.array([np.ones(len(x_train))]).T
xbar = np.concatenate((one, x_train), axis=1)
A = np.dot(xbar.T, xbar)
b = np.dot(xbar.T, y_train)
w = np.dot(np.linalg.pinv(A), b)
print(w)

[[ 0.04306436]
 [ 0.0089892 ]
 [-0.00047742]
 [ 0.00260218]
 [ 0.00808634]
 [ 0.00708535]]


In [37]:
one_test = np.array([np.ones(len(x_test))]).T
xbar_test = np.concatenate((one_test, x_test), axis=1)
y_predict = np.dot(xbar_test, w)
print(y_predict)

[[0.91012272]
 [0.78452963]
 [1.22339369]
 [0.96085817]
 [0.96836123]
 [1.05009561]
 [1.19694736]
 [1.0521678 ]
 [0.9936207 ]
 [0.68503543]
 [0.78429172]
 [0.77109845]
 [1.19748204]
 [1.06844174]
 [0.99721921]
 [1.03380704]
 [1.14558205]
 [1.19228584]
 [1.29236178]
 [1.26252546]]


In [38]:
mean = sum(y_test - y_predict) / len(y_test)
print("Mean: ", mean)
variance = sum((y_test - mean)**2)
print("Variance: ", variance)   

Mean:  [0.07998862]
Variance:  [26.9469683]
