Import các thư viện cần thiết

In [6]:
import numpy as np  
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score

Đọc dữ liệu từ file "framingham.cvs"

In [4]:
data = pd.read_csv('D:/Code/python/mat3533/practice03/data/framingham.csv')
data.dropna(how="any", axis=0, inplace=True)
data.head()

male  age  education  currentSmoker  cigsPerDay  BPMeds  prevalentStroke  \
0     1   39        4.0              0         0.0     0.0                0   
1     0   46        2.0              0         0.0     0.0                0   
2     1   48        1.0              1        20.0     0.0                0   
3     0   61        3.0              1        30.0     0.0                0   
4     0   46        3.0              1        23.0     0.0                0   

   prevalentHyp  diabetes  totChol  sysBP  diaBP    BMI  heartRate  glucose  \
0             0         0    195.0  106.0   70.0  26.97       80.0     77.0   
1             0         0    250.0  121.0   81.0  28.73       95.0     76.0   
2             0         0    245.0  127.5   80.0  25.34       75.0     70.0   
3             1         0    225.0  150.0   95.0  28.58       65.0    103.0   
4             0         0    285.0  130.0   84.0  23.10       85.0     85.0   

   TenYearCHD  
0           0  
1           0  
2           0  
3           1  
4           0

Chia dữ liệu thành tập Traning - Test với tỉ lệ 7:3

In [15]:
x = data.iloc[:, [i for i in range(0, 15)]]
y = data.iloc[:, 15]
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)

Sử dụng mô hình hồi quy logistic huấn luyện tập Traning và dự đoán trên tập Test

In [10]:
model = LogisticRegression()
model.fit(x_train, y_train)
y_predict = model.predict(x_test)
print(y_predict)

[0 0 0 ... 0 0 0]


c:\Users\Admin\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Tính độ đo Accuracy

In [11]:
accuracy_score(y_predict, y_test, normalize=True)

0.8413855970829535

Tính độ đo Precision

In [13]:
precision_score(y_test, y_predict, average=None)

array([0.84516129, 0.5       ])

Tính độ đo Recall

In [14]:
recall_score(y_test, y_predict, average=None)

array([0.99349946, 0.03448276])