Import các thư viện cần thiết

In [98]:
import numpy as np
import pandas as pd
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score

Đọc dữ liệu từ file "Admission_Predict.csv"

In [99]:
data = pd.read_csv("D:/Code/python/mat3533/practice03/data/Admission_Predict.csv")
data.describe()

Serial No.   GRE Score  TOEFL Score  University Rating         SOP  \
count  400.000000  400.000000   400.000000         400.000000  400.000000   
mean   200.500000  316.807500   107.410000           3.087500    3.400000   
std    115.614301   11.473646     6.069514           1.143728    1.006869   
min      1.000000  290.000000    92.000000           1.000000    1.000000   
25%    100.750000  308.000000   103.000000           2.000000    2.500000   
50%    200.500000  317.000000   107.000000           3.000000    3.500000   
75%    300.250000  325.000000   112.000000           4.000000    4.000000   
max    400.000000  340.000000   120.000000           5.000000    5.000000   

             LOR         CGPA    Research  Chance of Admit   
count  400.000000  400.000000  400.000000        400.000000  
mean     3.452500    8.598925    0.547500          0.724350  
std      0.898478    0.596317    0.498362          0.142609  
min      1.000000    6.800000    0.000000          0.340000  
25%      3.000000    8.170000    0.000000          0.640000  
50%      3.500000    8.610000    1.000000          0.730000  
75%      4.000000    9.062500    1.000000          0.830000  
max      5.000000    9.920000    1.000000          0.970000

a. Phân loại bằng phương pháp hồi quy Logistic

Lấy các cột dữ liệu vào các mảng X1, X2, ...

In [100]:
sn = data['Serial No.'].tolist()

gre = data['GRE Score'].tolist()
X1 = np.asarray(gre)

tfl = data['TOEFL Score'].tolist()
X2 = np.asarray(tfl)

unirt = data['University Rating'].tolist()
X3 = np.asarray(unirt)

sop = data['SOP'].tolist()
X4 = np.asarray(sop)

lor1 = data['LOR '].tolist()
X5 = np.asarray(lor1)

cgpa1 = data['CGPA'].tolist()
X6 = np.asarray(cgpa1)

research_exp = data['Research'].tolist()
X7 = np.asarray(research_exp)

prob_Admit = data['Chance of Admit '].tolist()
Yt = np.asarray(prob_Admit)

Chọn ra 350 dòng đầu làm dữ liệu training, phần còn lại là dữ liệu test.

In [101]:
X = np.concatenate(([X1], [X2], [X3], [X4], [X5], [X6], [X7]), axis=0).T
Y = np.array([1 if y >= 0.75 else 0 for y in Yt])
x_train = X[:350]
x_test = X[350:]
y_train = Y[:350]
y_test = Y[350:]

Bổ sung cột X0 ≡ 1 vào bên trái của ma trận X để được Xbar.

In [102]:
one_train = np.ones((x_train.shape[0], 1))
Xbar_train = np.concatenate((one_train, x_train), axis = 1)

Các hàm tính toán Logistic Regression

In [103]:
def sigmoid(s):
    return 1 / (1 + np.exp(-s))

def logistic_sigmoid_regression(x, y, w_init, eta, tol = 1e-4, max_count = 10000):
    w = [w_init]
    N = x.shape[1]
    d = x.shape[0]
    count = 0
    check_w_after = 20

    while count < max_count:
        mix_id = np.random.permutation(N)
        for i in range(N):
            xi = x[:, i].reshape(d, 1)
            yi = y[i]
            zi = sigmoid(np.dot(w[-1].T, xi))
            w_new = w[-1] + eta * (yi - zi) * xi
            count += 1
            if count % check_w_after == 0:
                if np.linalg.norm(w_new - w[-check_w_after]) < tol:
                    return w
                
            w.append(w_new)
    return w

Tính các hệ số của mô hình 

In [107]:
eta = 0.05
d = Xbar_train.shape[1]
w_init = np.random.randn(d, 1) 
w = logistic_sigmoid_regression(Xbar_train.T, y_train, w_init, eta, tol = 1e-4, max_count= 10000)
print(w[-1])

[[ -2.42905952]
 [-48.44226561]
 [132.95596359]
 [ 46.9384414 ]
 [ 52.96024009]
 [ 23.70329645]
 [ 16.84151464]
 [ 33.80829013]]


C:\Users\Admin\AppData\Local\Temp\ipykernel_7264\1977574643.py:2: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-s))


Dự đoán dữ liệu Test

In [108]:
one_test = np.ones((x_test.shape[0], 1))
Xbar_test = np.concatenate((one_test, x_test), axis = 1)

y_predict = np.round(sigmoid(np.dot(Xbar_test, w[-1])), decimals=0)
print(y_predict)

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]]


C:\Users\Admin\AppData\Local\Temp\ipykernel_7264\1977574643.py:2: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-s))


Tính độ đo Accuracy

In [70]:
accuracy_score(y_test, y_predict, normalize=True)

0.64

Tính toán độ đo Precision

In [71]:
precision_score(y_test, y_predict, average=None)

array([0.60869565, 1.        ])

Tính toán độ đo Recall

In [72]:
recall_score(y_test, y_predict, average=None)

array([1.        , 0.18181818])

b. Bài tập thực hành: Dự đoán khả năng bằng hồi quy tuyến tính

Tính các hệ số của mô hình

In [73]:
A = np.dot(Xbar_train.T, Xbar_train)
b = np.dot(Xbar_train.T, y_train)
w = np.dot(np.linalg.pinv(A), b)
print(w)

[-4.46299686e+00  4.01395627e-03  7.65467155e-03  5.78601109e-02
  3.35707410e-02  3.71372646e-02  2.68856682e-01  1.41900277e-01]


Dự đoán cho dữ liệu Test

In [77]:
ỏne_test =  np.ones((x_test.shape[0], 1))
Xbar_test = np.concatenate((one_test,x_test), axis=1)
y_predict = np.dot(Xbar_test, w)
print(y_predict)

[ 0.40210911  0.65392761  0.17399705  0.1024467  -0.14750441  0.11678085
  0.62332641  0.16766756 -0.07088742  0.15225096  0.62988256  0.9681033
  1.02351026  0.11240566  0.54849969  0.83547789  0.45991561 -0.27455378
 -0.24474133  0.03259461  0.07763005  0.70278745  1.05595776  0.483483
 -0.06240163 -0.13448527 -0.26447662 -0.31843511 -0.22201192  0.20471689
  0.58380324  0.4983564   0.8125356   0.13168636  1.11227099  1.20218854
 -0.00793355  0.06360949 -0.19492968  0.49885134  0.06924584  0.30258033
  0.79245315  0.2885419   0.86176859  0.67296188  0.65604642  0.99855837
  0.37797732  1.05614619]


Tính trung bình bình phương sai số

In [79]:
print(sum((y_predict - y_test)**2) / len(y_test))

0.09589505693058965


c. Bài tập tự thực hành: Hãy sử dụng phương pháp Naïve Bayes phù hợp để phân loại dữ liệu

In [81]:
from sklearn.naive_bayes import GaussianNB

In [84]:
model_sk = GaussianNB()
model_sk.fit(x_train, y_train)

GaussianNB()

In [85]:
y_predict = model_sk.predict(x_test)
print(y_predict)

[0 1 0 0 0 0 1 0 0 0 1 1 1 0 0 1 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 0 1 0 1 1 0
 0 0 1 0 0 1 0 1 1 1 1 0 1]


Tính độ đo accuracy

In [110]:
accuracy_score(y_test, y_predict, normalize=True)

0.64

Tính độ đo Precision

In [88]:
precision_score(y_test, y_predict, average=None)

array([0.87096774, 0.94736842])

Tính độ đo Recall

In [89]:
recall_score(y_test, y_predict, average=None)

array([0.96428571, 0.81818182])

d. Sử dụng thư viện Scikit-Learn: thực nghiệm lại các ví dụ 1 và 2.

In [93]:
import numpy as np  
from sklearn.linear_model import LogisticRegression

Ví dụ 1:

In [94]:
x = np.array([0.50, 0.75, 1.00, 1.25, 1.50, 1.75, 1.75, 2.00, 2.25, 2.50,  
              2.75, 3.00, 3.25, 3.50, 4.00, 4.25, 4.50, 4.75, 5.00, 5.50])
y = np.array([0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1])

In [95]:
logReg = LogisticRegression()
x = x.reshape(-1, 1)
logReg.fit(x, y)
y_predict = logReg.predict(x)
print(y_predict)
print(logReg.coef_)

[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1]
[[1.14860386]]


Ví dụ 2:

In [96]:
np.random.seed(22)
means = [[2, 2], [4, 2]]
cov = [[.7, 0], [0, .7]]
N = 20
X1 = np.random.multivariate_normal(means[0], cov, N)
X2 = np.random.multivariate_normal(means[1], cov, N)
X = np.concatenate((X1, X2), axis = 0)
Y = np.concatenate((np.zeros((1, N)), np.ones((1, N))), axis = 1).T
print(X)

[[ 1.92306918  0.775673  ]
 [ 2.90509186  1.7997662 ]
 [ 1.58909188  1.16143907]
 [ 2.76874122  1.07663514]
 [ 2.52416203  1.53020387]
 [ 2.02414192  1.80692632]
 [ 2.49174878  2.62943405]
 [ 1.11439322  2.88348991]
 [ 2.62561276  2.89077234]
 [ 3.27183166  0.75454543]
 [ 3.55617919  0.66250438]
 [ 1.45945603  2.28222634]
 [ 2.87575608  2.52637908]
 [ 2.30375703  2.46497356]
 [ 1.08925412  2.01982447]
 [ 4.09096119 -0.08330889]
 [ 1.80350003  1.91837255]
 [ 1.25827634  1.8856175 ]
 [ 2.08532169  1.79005729]
 [ 1.9340609   1.09208652]
 [ 4.49775285  1.46545116]
 [ 3.07311718  3.76212796]
 [ 3.52528933  1.59844519]
 [ 2.39091046  2.33431976]
 [ 3.12302646  1.41945943]
 [ 4.62359547  2.44921113]
 [ 3.38696098  2.46494505]
 [ 4.36167918  1.88637824]
 [ 3.21261415  2.40558547]
 [ 2.71754956  2.33882965]
 [ 4.01073111  0.96947283]
 [ 3.11892586  4.10522222]
 [ 2.29402636  2.07905375]
 [ 3.7365999   2.41022672]
 [ 4.29699439  2.79542218]
 [ 4.63617269  2.00962462]
 [ 2.84870815  1.77280105]
 

In [97]:
logReg = LogisticRegression()
# Training & compute weights w
logReg.fit(X, Y)
# For new data X_test, predict
Y_predict = logReg.predict(X)
print(Y_predict)
# For showing of w
print(logReg.coef_)

[0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 0.
 0. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 0. 1. 1. 0.]
[[1.69485631 1.04015835]]


c:\Users\Admin\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
